/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wind_ndk_gif_GifFrame */

#ifndef _Included_com_wind_ndk_gif_GifFrame
#define _Included_com_wind_ndk_gif_GifFrame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wind_ndk_gif_GifFrame
 * Method:    native_init
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Lcom/wind/ndk/gif/GifFrame;
 */
JNIEXPORT jobject JNICALL Java_com_wind_ndk_gif_GifFrame_native_1init__Ljava_lang_Object_2Ljava_lang_String_2
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_wind_ndk_gif_GifFrame
 * Method:    native_init
 * Signature: (Ljava/lang/Object;)Lcom/wind/ndk/gif/GifFrame;
 */
JNIEXPORT jobject JNICALL Java_com_wind_ndk_gif_GifFrame_native_1init__Ljava_lang_Object_2
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_wind_ndk_gif_GifFrame
 * Method:    nativeGetFrame
 * Signature: (JLjava/lang/Object;I)J
 */
JNIEXPORT jlong JNICALL Java_com_wind_ndk_gif_GifFrame_nativeGetFrame
  (JNIEnv *, jobject, jlong, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
